name: Build Background Clicker TW

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019 # 使用相容性最高的 Windows 2019 環境

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore BackgroundClicker.sln

    - name: Build Solution
      run: msbuild BackgroundClicker.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: BackgroundClicker-繁體中文免安裝版
        path: |
          **/bin/Release/*.exe
          **/bin/Release/*.dll
